name: Regression Test Pipeline

on:
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  Regression-Test-Prime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install httpyac
        run: npm install -g httpyac

      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install httpyac
        run: pip install junit2html
  
      - name: Run regression tests and generate results files
        run: pnpm gen-regression-test-results
          
      - name: Set up environment variables
        run: |
          echo "DATETIME=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Commit and push result
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "test: introduce ${{ env.DATETIME }} regression test results"
          git push
